spring.application.name=auth-service
server.port=9495
#spring.profiles.active=doker

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://172.26.238.72:5432/user_service_db
spring.datasource.username=user_service_user
spring.datasource.password=userpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Boot?s bundled Logback configuration doesn?t enable ANSI color codes for LOGS
# This forces ANSI color codes in the console (INFO = green, WARN = yellow, ERROR = red, etc.).
# Most modern IDE consoles (IntelliJ, VS Code) and terminals (PowerShell, bash, zsh) do. If you?re running inside Docker, you may need tty: true in your compose file.
# IN LOGBACK-SPRING.XML : INSIDE CONSOLE-APPENDER FOR PATTERN : <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %logger{36} - %msg [app=${appName} traceId=%X{traceId:-} spanId=%X{spanId:-}]%n</pattern>
# ? %highlight(%-5level) applies color based on log level.
spring.output.ansi.enabled=always


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#eureka.instance.instance-id=${spring.application.name}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90


#Enabling the cache
spring.cache.type=redis
# 600000s = 10 minutes OR 3600s
# 600,000 ms = 10 minutes suggested correction from above
# 600 seconds = 10 minutes suggested correction
spring.cache.redis.time-to-live=600s
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Resilience4j Properties
# for Resilience4j health endpoint of actuator is necessary and health endpoint should be exposed and included
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,prometheus,env
management.endpoint.health.show-details=always


# 100% for development : means 1.0 is 100% sampling for development only not for production
# 0.1 for production
management.tracing.sampling.probability=1.0


management.tracing.export.otlp.enabled=true
management.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# Ensures metrics are actually exported to OTLP (Mimir in LGTM).
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics


# Export logs to Loki via OTLP
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

# Sets the default log level for all classes in your com.learncicd.userservice package to WARN.
# Means only WARN, ERROR, and FATAL logs will appear ? suppresses INFO and DEBUG.
#logging.level.com.learncicd.authservice=info

# Include traceId/spanId in log pattern
#logging.pattern.level="%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

# OTel Logback Appender
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


# Adds a custom tag application=USER-SERVICE to all metrics exported by Micrometer/OpenTelemetry.
# Useful in Grafana dashboards to filter metrics by service name (e.g., user-service vs auth-service).
#management.metrics.tags.application=${spring.application.name}-METRICS-TAG
management.metrics.tags.application=AUTH-SERVICE-METRICS-TAG
#management.metrics.tags.environment=dev

