spring.application.name=api-gateway
server.port=9595

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# The prefer-ip-address: true property ensures that clients register using their IP address instead of hostname.
eureka.instance.prefer-ip-address=true

#spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true


# Resilience4j Properties
# for Resilience4j health endpoint of actuator is necessary and health endpoint should be exposed and included
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always

# API-Gateway Layer : RateLimiter, TimeLimiter, CircuitBreaker BUT NO RETRY, NO BULKHEAD
# resilience4j.bulkhead.metrics.enabled=true
resilience4j.timelimiter.metrics.enabled=true
resilience4j.ratelimiter.metrics.enabled=true
resilience4j.circuitbreaker.metrics.enabled=true

# WHEN WE DEFINE INSTANCE AS default, IT WILL BE APPLIED TO ALL THE SERVICES ?
# EXAMPLE : resilience4j.ratelimiter.configs.default.limit-for-period=10

# Gateway is reactive (WebFlux). Timeout is usually handled better with: this is more reliable than Resilience4j TimeLimiter at gateway.
# Recommended: use Gateway httpclient timeout instead.
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=5000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=5s

# TimeLimiter requires async return type
# Enable Circuit Breaker for Timeouts
# With this configuration, the circuit breaker will be OPEN, when the remote service is taking more than 5 seconds to send back the response.
resilience4j.timelimiter.instances.PROJECT-BOOKMARK-TL.timeout-duration.=5s
# here no instances are configured in API-Gateway so configuring default instance timeout duration
# resilience4j.timelimiter.configs.default.timeout-duration=5s
resilience4j.timelimiter.instances.USER-SERVICE-TL.timeout-duration=5s


# Resilience4J RateLimiter Properties
# The rate limiter will be configured to allow a maximum of 10 concurrent calls and a queue of 20 calls.
# resilience4j.ratelimiter.configs.default.limit-for-period=10
# resilience4j.ratelimiter.configs.default.limit-refresh-period=1s

resilience4j.ratelimiter.instances.PROJECT-BOOKMARK-RL.limit-for-period=10
resilience4j.ratelimiter.instances.PROJECT-BOOKMARK-RL.limit-refresh-period=1s

resilience4j.ratelimiter.instances.USER-SERVICE-RL.limit-for-period=10
resilience4j.ratelimiter.instances.USER-SERVICE-RL.limit-refresh-period=1s

resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.register-health-indicator=true
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.sliding-window-size=5
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.PROJECT-BOOKMARK-CB.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.USER-SERVICE-CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.register-health-indicator=true
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.sliding-window-size=5
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.USER-SERVICE-CB.permitted-number-of-calls-in-half-open-state=3


# Resilience4J Retry Properties : RETRY IS NOT IMPLEMENTED AT API-GATEWAY LAYER IN PRODUCTION
# Sometimes, the service can be unavailable due to a small network issue (or) any other minor issue, in those cases,
# it's better to retry the call instead of directly activating the Circuit Breaker.
# configuration will retry for a maximum of 3 times, with a wait of 5 seconds in between the retries.
# resilience4j.retry.instances.USER-SERVICE-RETRY.max-attempts=3
# resilience4j.retry.instances.USER-SERVICE-RETRY.wait-duration=5s

# Resilience4J Bulkhead Properties : BULKHEAD IS NOT IMPLEMENTED AT API-GATEWAY LAYER IN PRODUCTION
# The bulkhead will be configured to allow a maximum of 10 concurrent calls and a queue of 20 calls.
# resilience4j.bulkhead.instances.USER-SERVICE-BH.max-concurrent-calls=10
# resilience4j.bulkhead.instances.USER-SERVICE-BH.max-wait-duration=20s


#Redis Connection Config
# In Api-Gateway Redis is used for RateLimiting
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s




