spring.application.name=user-service
server.port=9494

#spring.cloud.config.uri=http://localhost:8888
#spring.config.import=optional:configserver:http://localhost:8888


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://172.26.238.72:5432/user_service_db
spring.datasource.username=user_service_user
spring.datasource.password=userpass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Spring Boot?s bundled Logback configuration doesn?t enable ANSI color codes for LOGS
# This forces ANSI color codes in the console (INFO = green, WARN = yellow, ERROR = red, etc.).
# Most modern IDE consoles (IntelliJ, VS Code) and terminals (PowerShell, bash, zsh) do. If you?re running inside Docker, you may need tty: true in your compose file.
# IN LOGBACK-SPRING.XML : INSIDE CONSOLE-APPENDER FOR PATTERN : <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %logger{36} - %msg [app=${appName} traceId=%X{traceId:-} spanId=%X{spanId:-}]%n</pattern>
# ? %highlight(%-5level) applies color based on log level.
spring.output.ansi.enabled=always

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

bookmark.service.url= http://localhost:3331/api/bookmarks



# Enable Circuit Breaker for OpenFeign
# spring.cloud.openfeign.circuitbreaker.enabled=true


#Resilience4j Properties
# for Resilience4j health endpoint of actuator is necessary and health endpoint should be exposed and included
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,prometheus,env
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always



# AT Service LAYER ? Service Calls : TimeLimiter, Bulkhead, CircuitBreaker, Retry BUT NO RATELIMITER(BECAUSE RATELIMITER IS IMPLEMENTED AT API-GATEWAY)
#  Ensures circuitbreaker, retry, and bulkhead metrics will flow into Grafana.
# Ensures Resilience4j publishes metrics (e.g., circuit breaker states, retry counts, bulkhead usage).
# These flow into Micrometer ? OTLP ? Grafana Mimir.
# resilience4j.timelimiter.metrics.enabled=true
resilience4j.bulkhead.metrics.enabled=true
resilience4j.circuitbreaker.metrics.enabled=true
resilience4j.retry.metrics.enabled=true


# TimeLimiter requires async return type
# Enable Circuit Breaker for Timeouts
# With this configuration, the circuit breaker will be OPEN, when the remote service is taking more than 5 seconds to send back the response.
# resilience4j.timelimiter.instances.USER-PROJECT-BOOKMARK-TL.timeoutDuration=2s

# Resilience4J Retry Properties
# Sometimes, the service can be unavailable due to a small network issue (or) any other minor issue, in those cases,
# it's better to retry the call instead of directly activating the Circuit Breaker.
# configuration will retry for a maximum of 3 times, with a wait of 5 seconds in between the retries. :: waitDuration=500ms. Retries should be fast + limited.
# resilience4j.retry.configs.USER-PROJECT-BOOKMARK-RETRY.max-attempts=3
# resilience4j.retry.configs.USER-PROJECT-BOOKMARK-RETRY.wait-duration=5s
# Since your downstream service returns business errors (401 Unauthorized, 403 Forbidden, 422 Unprocessable Entity) wrapped in CustomException, you should ignore those so Retry doesn?t waste attempts:
# max-attempts=3 ? The system will try the failed call up to 3 times in total (1 original attempt + 2 retries).
resilience4j.retry.instances.USER-PROJECT-BOOKMARK-RETRY.max-attempts=3
# wait-duration=300ms ? Between each retry, it will pause for 300 milliseconds before trying again.
resilience4j.retry.instances.USER-PROJECT-BOOKMARK-RETRY.wait-duration=300ms
# ignore-exceptions ? A blacklist. These exception types will not be retried, even if they match the whitelist. Example: CustomException with 401/403/422.
#  Never retry business errors. Ignore business errors (401/403/422) so they propagate immediately to your GlobalExceptionHandler.
resilience4j.retry.instances.USER-PROJECT-BOOKMARK-RETRY.ignore-exceptions=com.learncicd.userservice.exception.CustomException
# retry-exceptions ? A whitelist. Only these exception types will trigger retries. Example: IOException, TimeoutException.
# Only retry on transient/system errors(timeouts, IO/network glitches)
resilience4j.retry.instances.USER-PROJECT-BOOKMARK-RETRY.retry-exceptions=java.io.IOException,java.util.concurrent.TimeoutException


# Resilience4J Bulkhead Properties
# The bulkhead will be configured to allow a maximum of 10 concurrent calls and a queue of 20 calls.
# Bulkhead Limits simultaneous Feign calls to bookmark service. It Prevents thread exhaustion. Use SEMAPHORE type for Feign. THREADPOOL bulkhead better for async clients.
# resilience4j.bulkhead.configs.USER-PROJECT-BOOKMARK-BH.max-concurrent-calls=20
# resilience4j.bulkhead.configs.USER-PROJECT-BOOKMARK-BH.max-wait-duration=0
# max-concurrent-calls=20 ? At most 20 threads (calls) can enter this protected section at the same time. If more than 20 requests arrive, they WIll be queued or rejected depending on the wait duration.
resilience4j.bulkhead.instances.USER-PROJECT-BOOKMARK-BH.max-concurrent-calls=20
# max-wait-duration=3 ? If all 20 slots are busy, a new request will wait up to 3 seconds for a slot to free up. If no slot becomes available within that time, the request fails immediately.
resilience4j.bulkhead.instances.USER-PROJECT-BOOKMARK-BH.max-wait-duration=3

# Resilience4J Circuit Breaker Properties
# The circuit breaker will be configured to allow a maximum of 10 concurrent calls and a queue of 20 calls.
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.register-health-indicator=true
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.sliding-window-size=10
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.permitted-number-of-calls-in-half-open-state=3

# ?? List of exception classes that CircuitBreaker should completely ignore (not counted as success or failure).
#resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.ignore-exceptions=com.learncicd.userservice.exception.CustomException

# ?? List of exceptions that CircuitBreaker should treat as failures and increase failure count.
#resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.record-exceptions[]=

# ?? Custom Java predicate that dynamically decides which exceptions should be ignored by the CircuitBreaker.
# ?? Decides whether CircuitBreaker should completely ignore an exception.
# ignore-exception-predicate : Exception not counted at all
#resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.ignore-exception-predicate=com.learncicd.userservice.config.RecordFailurePredicate

# ?? Tells CircuitBreaker to ignore CustomException so it will NOT trigger fallback or increase failure count.
#resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.ignore-exceptions=com.learncicd.userservice.exception.CustomException

# ?? Custom predicate that decides whether a returned result (not exception) should be treated as a failure.
#resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.record-result-predicate=

# ?? Custom logic to decide which exceptions should be counted as failures by CircuitBreaker.
# record-failure-predicate tells the CircuitBreaker Do NOT treat CustomException (401, 403, 422 etc.) as failures
# record-failure-predicate : Exception counted as success or failure
resilience4j.circuitbreaker.instances.USER-PROJECT-BOOKMARK-CB.record-failure-predicate=com.learncicd.userservice.config.RecordFailurePredicate



# Resilience4J RateLimiter Properties
# RateLimiter: If bookmark-service is sensitive to traffic spikes, consider enabling a rate limiter (e.g., 10 requests per second).
# The rate limiter will be configured to allow a maximum of 10 concurrent calls and a queue of 20 calls.
# resilience4j.ratelimiter.configs.default.limit-for-period=10
# resilience4j.ratelimiter.configs.default.limit-refresh-period=1s
# resilience4j.ratelimiter.instances.USER-PROJECT-BOOKMARK-RL.limit-for-period=10
# resilience4j.ratelimiter.instances.USER-PROJECT-BOOKMARK-RL.limit-refresh-period=1s

# Feign default configuration
# We can set the connection and read timeouts that apply to every Feign Client in the application via the feign.client.config.default property set in our application.yml file:
# spring.cloud.openfeign.client.config.default ? applies globally to all Feign clients.
# spring.cloud.openfeign.client.config.<clientName> ? applies to a specific Feign client (the name must match the @FeignClient(name="BOOKMARK-PROJECT") exactly).
# Units are milliseconds.
# In production, you typically use both: Feign timeouts to guard sockets, and Resilience4j TimeLimiter to enforce business level response deadlines.
# max time to establish TCP connection
spring.cloud.openfeign.client.config.default.connect-timeout=2000
#  max time to wait for response
spring.cloud.openfeign.client.config.default.read-timeout=2000
# feign configure timeouts per Feign client instead of globally
spring.cloud.openfeign.client.config.BOOKMARK-PROJECT.connect-timeout=2000
spring.cloud.openfeign.client.config.BOOKMARK-PROJECT.read-timeout=2000

# 100% for development : means 1.0 is 100% sampling for development only not for production
# 0.1 for production
management.tracing.sampling.probability=1.0


management.tracing.export.otlp.enabled=true
management.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# Ensures metrics are actually exported to OTLP (Mimir in LGTM).
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

# Export logs to Loki via OTLP
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs


# Sets the default log level for all classes in your com.learncicd.userservice package to WARN.
# Means only WARN, ERROR, and FATAL logs will appear ? suppresses INFO and DEBUG.
#logging.level.com.learncicd.userservice=info
#.level.feign=warn
# Keeps Feign-related framework logs quiet unless something goes wrong.
#logging.level.org.springframework.cloud.openfeign=warn
# Ensures that whenever CustomException is logged, it?s treated as WARN
# Prevents stack traces or ERROR-level noise for expected business errors (401/403/422).
logging.level.com.learncicd.userservice.exception.CustomException=warn

# Include traceId/spanId in log pattern
#logging.pattern.level="%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"


# These properties only affect how logs are printed to the console or written to a file when you use Spring Boot?s default logging setup.
# OTel Logback Appender
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


# Adds a custom tag application=USER-SERVICE to all metrics exported by Micrometer/OpenTelemetry.
# Useful in Grafana dashboards to filter metrics by service name (e.g., user-service vs auth-service).
#management.metrics.tags.application=${spring.application.name}-METRICS-TAG
management.metrics.tags.application=USER-SERVICE-METRICS-TAG
#management.metrics.tags.environment=dev

# FOR DEVELOPMENT ONLY NOT FOR PRODUCTION(none or warn).
# Logs the HTTP method, URL, response status, and headers.So that traceId/spanId are flowing across services
# every call from user-service to BOOKMARK-PROJECT will show the trace headers in logs, proving context propagation is working.
# basic/full
spring.cloud.openfeign.client.config.default.logger-level=basic

