spring.application.name=discovery-service
server.port=8761

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
# default is 0.85
eureka.server.renewal-percent-threshold=0.85
# Self-Preservation Mode
eureka.server.enable-self-preservation=true

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF