spring.application.name=config-server
server.port=8888


# ? Git repository for configs
# Location of your Git repo holding externalized config files.
spring.cloud.config.server.git.uri=https://github.com/Pratheush/micro-cicd-config-server.git
# Clone the repo immediately when the server starts.
spring.cloud.config.server.git.clone-on-start=true
# Local folder where the repo will be cloned (leave empty for default).
# (here: inside your config-server project folder).
spring.cloud.config.server.git.basedir=./config-repo
# How often to check for changes; 0 means always fetch latest.
spring.cloud.config.server.git.refresh-rate=0


# ? Authentication (optional)
#  Credentials if your Git repo is private.
#spring.cloud.config.username=
#spring.cloud.config.password=


# ?? Client connection settings
# Default profile used if none is specified by the client.
spring.cloud.config.profile=default
# Max time to establish a TCP connection to Config Server.ms
spring.cloud.config.request-connect-timeout=2000
#  Max time to wait for a response from Config Server.ms
spring.cloud.config.request-read-timeout=5000


# ? Retry behavior
# How many times a client retries fetching config if it fails.
spring.cloud.config.retry.max-attempts=3
# Wait 1 second before the first retry.
spring.cloud.config.retry.initial-interval=1000
# Max wait between retries is 2 seconds.
spring.cloud.config.retry.max-interval=2000
# Each retry wait increases by 10% (exponential backoff).
spring.cloud.config.retry.multiplier=1.1

# ? Enable Config Server features
# Turns on Config Client support.
spring.cloud.config.enabled=true
# Allows clients to discover Config Server via Eureka.
spring.cloud.config.discovery.enabled=true
# The Eureka service ID for Config Server.
spring.cloud.config.discovery.service-id=configserver
# Fail startup immediately if config cannot be loaded.
spring.cloud.config.fail-fast=true
# Direct URI for Config Server (used if not via discovery).
spring.cloud.config.uri=http://localhost:8888
# Reload config when Spring context refreshes.
spring.cloud.config.initialize-on-context-refresh=true


