spring.application.name=project-bookmark
server.port=3331

spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:bookmarkdb
#spring.datasource.url=jdbc:h2:file:D:/rbt_micro/SampleMicroServiceRestTestWebClient/data/employeedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#enabling the H2 console
spring.h2.console.enabled=true

# custome H2 console url, Default is h2-console
spring.h2.console.path=/h2


spring.jpa.hibernate.ddl-auto=none

#spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

#Enabling the cache
spring.cache.type=redis
# 600000s = 10 minutes OR 3600s
spring.cache.redis.time-to-live=600000s
spring.data.redis.host=localhost
spring.data.redis.port=6379
