spring.application.name=project-bookmark
server.port=3331
#spring.profiles.active=doker

# Spring Boot?s bundled Logback configuration doesn?t enable ANSI color codes for LOGS
# This forces ANSI color codes in the console (INFO = green, WARN = yellow, ERROR = red, etc.).
# Most modern IDE consoles (IntelliJ, VS Code) and terminals (PowerShell, bash, zsh) do. If you?re running inside Docker, you may need tty: true in your compose file.
# IN LOGBACK-SPRING.XML : INSIDE CONSOLE-APPENDER FOR PATTERN : <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %logger{36} - %msg [app=${appName} traceId=%X{traceId:-} spanId=%X{spanId:-}]%n</pattern>
# ? %highlight(%-5level) applies color based on log level.
spring.output.ansi.enabled=always


spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:mem:bookmarkdb
#spring.datasource.url=jdbc:h2:file:D:/rbt_micro/SampleMicroServiceRestTestWebClient/data/employeedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#enabling the H2 console
spring.h2.console.enabled=true

# custome H2 console url, Default is h2-console
spring.h2.console.path=/h2



spring.jpa.hibernate.ddl-auto=none

#spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

#Enabling the cache
spring.cache.type=redis
# 600000s = 10 minutes OR 3600s
spring.cache.redis.time-to-live=600s
spring.data.redis.host=localhost
spring.data.redis.port=6379


#Resilience4j Properties
# for Resilience4j health endpoint of actuator is necessary and health endpoint should be exposed and included
management.endpoints.web.exposure.include=health,info,metrics,prometheus,env
management.endpoint.health.show-details=always


# 100% for development : means 1.0 is 100% sampling for development only not for production
# 0.1 for production
# 100% for development
# 0.1 for production
management.tracing.sampling.probability=1.0

management.tracing.export.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# Ensures metrics are actually exported to OTLP (Mimir in LGTM).
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

# Export logs to Loki via OTLP
management.logging.export.otlp.enabled=true
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs


management.defaults.metrics.export.enabled=true

# Prometheus endpoint also enabled ? Grafana can scrape metrics directly.
management.prometheus.metrics.export.enabled=true


#logging.level.com.example.pbookmark=info
#logging.level.org.springframework.cloud.gateway=info

# Include traceId/spanId in log pattern
#logging.pattern.level="%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"

# OTel Logback Appender
# Include traceId/spanId in log pattern
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Adds a custom tag application=USER-SERVICE to all metrics exported by Micrometer/OpenTelemetry.
# Useful in Grafana dashboards to filter metrics by service name (e.g., user-service vs auth-service).
#management.metrics.tags.application=${spring.application.name}-METRICS-TAG
management.metrics.tags.application=PROJECT-BOOKMARK-METRICS-TAG
#management.metrics.tags.environment=dev